spring:
  profiles:
    active: local

endpoints:
  jsonPlaceHolderDomain: https://jsonplaceholder.typicode.com/todos/

someConfiguration:
  value: "this is the value"
---
spring:
  profiles: local

endpoints:
  jsonPlaceHolderDomain: https://jsonplaceholder.typicode.com/todos/
---
spring:
    profiles: testStubbed

endpoints:
  jsonPlaceHolderDomain: https://jsonplaceholder.typicode.com/todos/
---
spring:
    profiles: testIntegration

endpoints:
  jsonPlaceHolderDomain: https://jsonplaceholder.typicode.com/todos/
  serverAddress: http://localhost:8080/
---
spring:
    profiles: prod

endpoints:
  jsonPlaceHolderDomain: https://jsonplaceholder.typicode.com/todos/
---
